language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install mock; fi
  - pip install -e .[tornado]
# command to run tests
script: py.test
